[package]
name = "px-in-the-middle"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.6.1", features = ["serde"] }
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["full"] }
hyper-util = { version = "0.1.6", features = ["full"] }
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
simple_logger = "5.0.0"
tokio = { version = "1.38.0", features = ["full"] }
tokio-macros = "2.3.0"
toml = "0.8.14"
