[package]
name = "px-in-the-middle"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.6.1", features = ["serde"] }
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["full"] }
hyper-util = { version = "0.1.6", features = ["full"] }
log = "0.4.22"
rustls-pemfile = "2.1.2"
rustls-platform-verifier = "0.3.2"
serde = { version = "1.0.204", features = ["derive"] }
simple_logger = "5.0.0"
tokio = { version = "1.38.0", features = ["full"] }
tokio-macros = "2.3.0"
tokio-rustls = "0.26.0"
toml = "0.8.14"
webpki-roots = "0.26.3"
