

bind = "localhost:8080"
remote = "http://localhost:8000/"
rewrite_host = false

# ssl_mode = "os"

ssl_mode = "dangerous"

# ssl_mode = "file"
# cafile = "./test_server/cert.pem"

graceful_shutdown_timeout = "2sec"

# server_ssl_trust = "./test-server/cert.pem"
# server_ssl_key = "./test-server/key.pem"

# log_headers=true

[filters]
test = { path = "^/test$", method = "GET" }
test2_and_below = { path = "^/test2/.*" }
post = { method = "POST" }

[actions]
no_log = { log = false, log_headers = false, log_request_body = false }
log_hdr = { log_headers = true }
log_body = { log_request_body = true }
to_google = { remote = "https://www.google.it", rewrite_host = true }

[rules]
r1 = { filter = "test", action = "to_google", disable_on = "(404)|(5..)", probability = 0.1, max_life = 10 }
r2 = { action = "no_log", keep_while = "200" }
r3 = { filters = ["test2_and_below","post"], actions = ["log_hdr","log_body"] }


