
bind = "localhost:8080"
remote = "http://localhost:8000/"
rewrite_host = true

# ssl_mode = "os"

ssl_mode = "dangerous"

# ssl_mode = "file"
# cafile = "./test_server/cert.pem"

graceful_shutdown_timeout = "2sec"

# server_ssl_trust = "./test-server/cert.pem"
# server_ssl_key = "./test-server/key.pem"

[filters]
f1 = { path = "^/test$", method = "GET", log_headers = true }
f2 = { path = "^/test2/.*", log_headers = true }
f3 = { method = "POST", log_request_body = true }

