
bind = "localhost:8080"
remote = "https://localhost:8000/"
rewrite_host = true
log_headers = true

# ssl_mode = "os"

ssl_mode = "dangerous"

# ssl_mode = "file"
# cafile = "./test_server/cert.pem"

graceful_shutdown_timeout = "2sec"

server_ssl_trust = "./test-server/cert.pem"
server_ssl_key = "./test-server/key.pem"

